name: Reusable Action

runs:
  using: 'composite'
  steps:
      - name: composite step
        id: composite_step
        env:
          my_step_var1: my step variable
        run: |
          echo "Composite step"
          echo "${{ env.My_var_1 }}"
        shell: bash
